### ISSUE TITLE
pdfjs viewer causes deprecation warning 

### ISSUE THREAD

**Issue by jorisvanzundert** [allefeld/atom-pdfjs-viewer#10]
Hi,

Thanks for this great Atom package!

Just wanted to let you know I get a deprecation warning if I use it.

```
atom core (1 deprecation)
Use require("electron").shell instead of require("shell")

Object.<anonymous> - /Applications/Atom.app/Contents/Resources/app.asar/exports/shell.js:4:6
Object.<anonymous> - /Applications/Atom.app/Contents/Resources/app.asar/exports/shell.js:9:3
Module._compile - <embedded>:11:149837
Object..js - <embedded>:11:153385
Module.load - internal/modules/cjs/loader.js:815:32
Module._load - internal/modules/cjs/loader.js:727:14
```

To be honest I don't quite understand how a Javascript plugin causes a deprecation warning in `atom core`. So, I am also not entirely sure if this should (also) be reported on the Atom repo. If you have any clues, I'm happy to hear.

Hope it's fixable.

Cheers
--Joris

**Comment by allefeld** [comment]
Thanks for the report! Should be fixed in the new version 1.0.1.

fixed by 6e1c006cf8060fd1a706f010d6c6e46868636ba0
