### ISSUE TITLE
FR: after reloading a modified PDF, keep the scroll position

### ISSUE THREAD

**Issue by avm99963** [allefeld/atom-pdfjs-viewer#12]
This is useful when writing long latex files which are constantly being built while editing.

I see there were some efforts to do this:

https://github.com/allefeld/atom-pdfjs-viewer/blob/a9c8c8890572c9c81dad1a38704320f0717b963a/lib/pdfjs-viewer-view.js#L247-L255

That snippets suggests that a workaround like the ones shared in https://github.com/mozilla/pdf.js/issues/11359#issuecomment-659154737 and https://github.com/mozilla/pdf.js/issues/11496#issuecomment-573650428 was tried unsuccessfully.

**Comment by allefeld** [comment]
The official solution would be to make sure the PDF ID does not change when the PDF is regenerated.
See: https://github.com/allefeld/atom-pdfjs-viewer/issues/3#issuecomment-622022837

But you're right, I also tried to hack this, unsuccessfully. Thanks for the pointers to a workaround, I'll look into that!
The drawback would be that then different documents might inherit each other's scroll position.

**Comment by allefeld** [comment]
I added code to implement the workaround from https://github.com/mozilla/pdf.js/issues/11359#issuecomment-659154737.
It is disabled by default, but can be enabled by a new package option "Override PDF ID".

**Comment by allefeld** [comment]
published with v1.3.0
