### ISSUE TITLE
Option to disable side bar by default

### ISSUE THREAD

**Issue by Tomaubier** [allefeld/atom-pdfjs-viewer#8]
Hi,
I've been using this package in conjunction with atom-latex for a few days now and I'm really enjoying the experience, awesome work! However a small detail drives me a bit crazy, I found that that the apparition of the side bar happing each time a document is build can be quite annoying, especially on a small laptop screen where the latter covers a good amount of the document. Would it be possible to add a option to disable this behaviour?
Thanks!
Tom

**Comment by allefeld** [comment]
Glad you like the package!

You mean the sidebar within the PDF viewer (bookmarks etc.)? It may be possible to suppress that from my side, though my package is just a wrapper for `PDF.js`.

But a better way would be to generate the PDF differently. The standard behavior for a PDF viewer (followed by `pdf.js`) is to show bookmarks or not depending on a setting within the PDF file itself. If you use `hyperref`, the setting is called [`pdfpagemode`](http://mirrors.ctan.org/macros/latex/contrib/hyperref/doc/manual.html#x1-110003.7), which defaults to `UseOutlines`, i.e. to show the bookmarks panel. Setting that to `UseNone` should resolve the issue.

Please let me know if it works.

**Comment by allefeld** [comment]
> Please let me know if it works.
